<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Caveshrooms</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\</OutputPath>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>C:\Users\DJRic\AppData\Roaming\Vintagestory\VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VintagestoryLib">
      <HintPath>C:\Users\DJRic\AppData\Roaming\Vintagestory\VintagestoryLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VSSurvivalMod">
      <HintPath>C:\Users\DJRic\AppData\Roaming\Vintagestory\Mods\VSSurvivalMod.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>C:\Users\DJRic\AppData\Roaming\Vintagestory\Lib\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>C:\Users\DJRic\AppData\Roaming\Vintagestory\Lib\Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
